/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.emirhan.harrypotter;

import com.emirhan.harrypotter.PotterClient.potterCharacters;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;


/**
 *
 * @author emirh
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        // karakterler için root ekledim ve child node ları koydum.
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("HARRY POTTER"); 
//karakterler
        DefaultMutableTreeNode characters = new DefaultMutableTreeNode("Characters");
        DefaultMutableTreeNode harry = new DefaultMutableTreeNode("Harry");
        DefaultMutableTreeNode hermione = new DefaultMutableTreeNode("Hermione");
        DefaultMutableTreeNode colin = new DefaultMutableTreeNode("Colin");
        DefaultMutableTreeNode ron = new DefaultMutableTreeNode("Ron");
        DefaultMutableTreeNode dobby = new DefaultMutableTreeNode("Dobby");
        DefaultMutableTreeNode dumbledore = new DefaultMutableTreeNode("Dumbledore");
        DefaultMutableTreeNode flamel = new DefaultMutableTreeNode("Flamel");
        DefaultMutableTreeNode petunia = new DefaultMutableTreeNode("Petunia");
        DefaultMutableTreeNode snape = new DefaultMutableTreeNode("Snape");
        DefaultMutableTreeNode mcGonagall = new DefaultMutableTreeNode("mcGonagall");
        DefaultMutableTreeNode sirius = new DefaultMutableTreeNode("Sirius");
        root.add(characters);
        characters.add(harry);
        characters.add(hermione);
        characters.add(colin);
        characters.add(ron);
        characters.add(dobby);
        characters.add(dumbledore);
        characters.add(flamel);
        characters.add(petunia);
        characters.add(snape);
        characters.add(mcGonagall);
        characters.add(sirius);
        // büyüler için root ekledim ve child node ları koydum.
        

        DefaultTreeModel tree_model = new DefaultTreeModel(root);
        jTree1.setModel(tree_model);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBackground(new java.awt.Color(153, 204, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.blue));
        jTable1.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTree1.setBackground(new java.awt.Color(102, 0, 153));
        jTree1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 51, 255)));
        jTree1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 12)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        
        try {
            DefaultTableModel potterModelCharacter = new DefaultTableModel();
            potterModelCharacter.setRowCount(1);
            potterModelCharacter.setColumnIdentifiers(new Object[] {"Name", "House", "blood status", "species", "role"} );
            TreePath tp = jTree1.getPathForLocation(evt.getX(), evt.getY());
            String nodeName=tp.getLastPathComponent().toString();


            switch (nodeName) {
                case "Harry":
                    //0,0 column ve row
                    charactervalueSetter(potterModelCharacter,"5a12292a0f5ae10021650d7e",0,0);
                    charactervalueSetter(potterModelCharacter,"5a12292a0f5ae10021650d7e",0,1);
                    charactervalueSetter(potterModelCharacter,"5a12292a0f5ae10021650d7e",0,2);
                    charactervalueSetter(potterModelCharacter,"5a12292a0f5ae10021650d7e",0,3);
                    charactervalueSetter(potterModelCharacter,"5a12292a0f5ae10021650d7e",0,4);
                    jTable1.setModel(potterModelCharacter);
                    break;
                case "Hermione":
                    charactervalueSetter(potterModelCharacter,"5a109af13dc2080021cd877a",0,0);
                    charactervalueSetter(potterModelCharacter,"5a109af13dc2080021cd877a",0,1);
                    charactervalueSetter(potterModelCharacter,"5a109af13dc2080021cd877a",0,2);
                    charactervalueSetter(potterModelCharacter,"5a109af13dc2080021cd877a",0,3);
                    charactervalueSetter(potterModelCharacter,"5a109af13dc2080021cd877a",0,4);
                    jTable1.setModel(potterModelCharacter);
                    break;
                case "Colin":
                    charactervalueSetter(potterModelCharacter,"5a10944f3dc2080021cd8755",0,0);
                    charactervalueSetter(potterModelCharacter,"5a10944f3dc2080021cd8755",0,1);
                    charactervalueSetter(potterModelCharacter,"5a10944f3dc2080021cd8755",0,2);
                    charactervalueSetter(potterModelCharacter,"5a10944f3dc2080021cd8755",0,3);
                    charactervalueSetter(potterModelCharacter,"5a10944f3dc2080021cd8755",0,4);
                    jTable1.setModel(potterModelCharacter);
                    break;
                case "Ron":
                    charactervalueSetter(potterModelCharacter,"5a1239c80f5ae10021650dad",0,0);
                    charactervalueSetter(potterModelCharacter,"5a1239c80f5ae10021650dad",0,1);
                    charactervalueSetter(potterModelCharacter,"5a1239c80f5ae10021650dad",0,2);
                    charactervalueSetter(potterModelCharacter,"5a1239c80f5ae10021650dad",0,3);
                    charactervalueSetter(potterModelCharacter,"5a1239c80f5ae10021650dad",0,4);
                    jTable1.setModel(potterModelCharacter);
                    break;
                case "Dobby":
                    charactervalueSetter(potterModelCharacter,"5a123c260f5ae10021650db9",0,0);
                    charactervalueSetter(potterModelCharacter,"5a123c260f5ae10021650db9",0,1);
                    charactervalueSetter(potterModelCharacter,"5a123c260f5ae10021650db9",0,2);
                    charactervalueSetter(potterModelCharacter,"5a123c260f5ae10021650db9",0,3);
                    charactervalueSetter(potterModelCharacter,"5a123c260f5ae10021650db9",0,4);
                    jTable1.setModel(potterModelCharacter);
                    break;
                case "Dumbledore":
                    charactervalueSetter(potterModelCharacter,"5a1097653dc2080021cd8763",0,0);
                    charactervalueSetter(potterModelCharacter,"5a1097653dc2080021cd8763",0,1);
                    charactervalueSetter(potterModelCharacter,"5a1097653dc2080021cd8763",0,2);
                    charactervalueSetter(potterModelCharacter,"5a1097653dc2080021cd8763",0,3);
                    charactervalueSetter(potterModelCharacter,"5a1097653dc2080021cd8763",0,4);
                    jTable1.setModel(potterModelCharacter);
                    break;
                case "Flamel":
                    charactervalueSetter(potterModelCharacter,"5a10995b3dc2080021cd8770",0,0);
                    charactervalueSetter(potterModelCharacter,"5a10995b3dc2080021cd8770",0,1);
                    charactervalueSetter(potterModelCharacter,"5a10995b3dc2080021cd8770",0,2);
                    charactervalueSetter(potterModelCharacter,"5a10995b3dc2080021cd8770",0,3);
                    charactervalueSetter(potterModelCharacter,"5a10995b3dc2080021cd8770",0,4);
                    
                    jTable1.setModel(potterModelCharacter);
                    break;
                case "Petunia":
                    charactervalueSetter(potterModelCharacter,"5a1097aa3dc2080021cd8767",0,0);
                    charactervalueSetter(potterModelCharacter,"5a1097aa3dc2080021cd8767",0,1);
                    charactervalueSetter(potterModelCharacter,"5a1097aa3dc2080021cd8767",0,2);
                    charactervalueSetter(potterModelCharacter,"5a1097aa3dc2080021cd8767",0,3);
                    charactervalueSetter(potterModelCharacter,"5a1097aa3dc2080021cd8767",0,4);
                    
                    jTable1.setModel(potterModelCharacter);
                    break;
                case "Snape":
                    charactervalueSetter(potterModelCharacter,"5a1233bc0f5ae10021650d97",0,0);
                    charactervalueSetter(potterModelCharacter,"5a1233bc0f5ae10021650d97",0,1);
                    charactervalueSetter(potterModelCharacter,"5a1233bc0f5ae10021650d97",0,2);
                    charactervalueSetter(potterModelCharacter,"5a1233bc0f5ae10021650d97",0,3);
                    charactervalueSetter(potterModelCharacter,"5a1233bc0f5ae10021650d97",0,4);
                    
                    jTable1.setModel(potterModelCharacter);
                    break;
                case "mcGonagall":
                    charactervalueSetter(potterModelCharacter,"5a1223ed0f5ae10021650d70",0,0);
                    charactervalueSetter(potterModelCharacter,"5a1223ed0f5ae10021650d70",0,1);
                    charactervalueSetter(potterModelCharacter,"5a1223ed0f5ae10021650d70",0,2);
                    charactervalueSetter(potterModelCharacter,"5a1223ed0f5ae10021650d70",0,3);
                    charactervalueSetter(potterModelCharacter,"5a1223ed0f5ae10021650d70",0,4);
                    
                    jTable1.setModel(potterModelCharacter);
                    break;
                case "Sirius":
                    charactervalueSetter(potterModelCharacter,"5a0fa7dcae5bc100213c2338",0,0);
                    charactervalueSetter(potterModelCharacter,"5a0fa7dcae5bc100213c2338",0,1);
                    charactervalueSetter(potterModelCharacter,"5a0fa7dcae5bc100213c2338",0,2);
                    charactervalueSetter(potterModelCharacter,"5a0fa7dcae5bc100213c2338",0,3);
                    charactervalueSetter(potterModelCharacter,"5a0fa7dcae5bc100213c2338",0,4);
                    
                    jTable1.setModel(potterModelCharacter);
                    break;
                default:
                    break;
            }
        } catch (java.lang.NullPointerException e) {

        }
 
    }//GEN-LAST:event_jTree1MouseClicked

    public DefaultTableModel charactervalueSetter(DefaultTableModel dtm , String id,int row ,int column){
        PotterClient client = new PotterClient();
        potterCharacters character = client.getCharacter(id);

        switch(column){
            case 0:
                if(dtm.getValueAt(dtm.getRowCount()-1, column)!=null)
                    dtm.setRowCount(dtm.getRowCount()+1);
                dtm.setValueAt(character.name,row,column);
                break;
            case 1:
                dtm.setValueAt(character.house,row,column);
                if(character.house == null)
                   dtm.setValueAt("    none",row,column);
                break;
            case 2:
                dtm.setValueAt(character.bloodStatus,row,column);
                if(character.bloodStatus == null)
                   dtm.setValueAt("    none",row,column);
                break;
            case 3:
                dtm.setValueAt(character.species,row,column);
                if(character.species == null)
                   dtm.setValueAt("    none",row,column);
                break;
            case 4:
                dtm.setValueAt(character.role,row,column);
                if(character.role == null)
                   dtm.setValueAt("      none",row,column);
                
            default:
                break;
        }

        return dtm;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    private DefaultMutableTreeNode DefaultMutableTreeNode(String harry_potter) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
